
OTHER_FILES += \
    swfm/demo.html \
    swfm/build.xml \
    swfm/swfm/classes/window.js \
    swfm/swfm/classes/widget.js \
    swfm/swfm/classes/url.js \
    swfm/swfm/classes/swfm-main.js \
    swfm/swfm/classes/setting.js \
    swfm/swfm/classes/rpc.js \
    swfm/swfm/classes/resource.js \
    swfm/swfm/classes/plugin.js \
    swfm/swfm/classes/path.js \
    swfm/swfm/classes/menu.js \
    swfm/swfm/classes/icons.js \
    swfm/swfm/classes/i18n.js \
    swfm/swfm/classes/event.js \
    swfm/swfm/classes/config.js \
    swfm/swfm/classes/component.js \
    swfm/swfm/classes/clipboard.js \
    swfm/swfm/locale/de.js \
    swfm/swfm/plugins/afs_actions/main.js \
    swfm/swfm/plugins/afs_actions/build.xml \
    swfm/swfm/plugins/afs_actions/action_set_acl.js \
    swfm/swfm/plugins/afs_actions/action_manage_groups.js \
    swfm/swfm/plugins/afs_actions/locale/de.js \
    swfm/swfm/plugins/archives/main.js \
    swfm/swfm/plugins/archives/build.xml \
    swfm/swfm/plugins/archives/action_view.js \
    swfm/swfm/plugins/archives/action_create.js \
    swfm/swfm/plugins/archives/locale/de.js \
    swfm/swfm/plugins/base_actions/main.js \
    swfm/swfm/plugins/base_actions/build.xml \
    swfm/swfm/plugins/base_actions/action_rename.js \
    swfm/swfm/plugins/base_actions/action_new_folder.js \
    swfm/swfm/plugins/base_actions/action_move.js \
    swfm/swfm/plugins/base_actions/action_delete.js \
    swfm/swfm/plugins/base_actions/action_copy.js \
    swfm/swfm/plugins/base_actions/locale/de.js \
    swfm/swfm/plugins/esource_viewer/plugin.js \
    swfm/swfm/plugins/esource_viewer/locale/de.js \
    swfm/swfm/themes/default/theme.js \
    swfm/swfm/themes/default/style.css \
    swfm/swfm/themes/default/README \
    swfm/swfm/widgets/treemenu/widget.js \
    swfm/swfm/widgets/treemenu/locale/de.js \
    swfm/swfm/widgets/search/widget.js \
    swfm/swfm/widgets/search/locale/de.js \
    swfm/swfm/widgets/browser/css/main.css \
    swfm/swfm/widgets/browser/widget.js \
    swfm/swfm/widgets/browser/locale/de.js \
    swfm/swfm/plugins/example/plugin.js \
    swfm/swfm/plugins/example/locale/de.js \
    swfm/swfm/plugins/extra/plugin.js \
    swfm/swfm/plugins/extra/locale/de.js \
    swfm/swfm/plugins/image_viewer/plugin.js \
    swfm/swfm/plugins/image_viewer/locale/de.js \
    swfm/swfm/plugins/new_file/plugin.js \
    swfm/swfm/plugins/setting/plugin.js \
    swfm/swfm/plugins/setting/locale/de.js \
    localconfig/dev/js/jquery-1.4.1.min.js \
    localconfig/dev/js/jquery.json-2.2.min.js \
    localconfig/local/local.php \
    localconfig/dev/local.php \
    localconfig/dev/json-test.html \
    localconfig/dev/index.php \
    localconfig/prod/local.php \
    localconfig/prod/index.php \
    translationHelper.py \
    Makefile \
    files.txt \
    build-local.sh \
    build.sh \
    backend-php/Makefile \
    backend-php/GPLv3 \
    backend-php/src/index.php \
    backend-php/src/commands/setting_actions.php \
    backend-php/src/commands/search_actions.php \
    backend-php/src/commands/new_file.php \
    backend-php/src/commands/base_direct_commands.php \
    backend-php/src/commands/base_actions.php \
    backend-php/src/commands/archive_actions.php \
    backend-php/src/commands/afs_special_actions.php \
    backend-php/src/config/new_file.cfg.dist \
    backend-php/src/config/local.php.dist \
    backend-php/src/install/style.css \
    backend-php/src/install/libinstall.php \
    backend-php/src/install/index.php \
    backend-php/src/lib/AFS/mimetype.php \
    backend-php/src/lib/AFS/mime.types \
    backend-php/src/lib/AFS/libafs.php \
    backend-php/src/lib/archives/archives.php \
    backend-php/src/lib/search/libsearch.php \
    backend-php/src/lib/SmartWFM/validate.php \
    backend-php/src/lib/SmartWFM/tools.php \
    backend-php/src/lib/SmartWFM/mime.types \
    backend-php/src/lib/SmartWFM/main.php \
    swfm/tools/ext-doc/swfm.xml \
    swfm/tools/ext-doc/README.SmartWFM \
    swfm/tools/ext-doc/template/swfm/welcome.html \
    swfm/tools/ext-doc/template/swfm/template.xml \
    swfm/tools/ext-doc/template/swfm/source-wrap.html \
    swfm/tools/ext-doc/template/swfm/license.txt \
    swfm/tools/ext-doc/template/swfm/index.html \
    swfm/tools/ext-doc/template/swfm/tpl/tree.xsl \
    swfm/tools/ext-doc/template/swfm/tpl/class.xsl
